apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-records-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-records-service
  template:
    metadata:
      labels:
        app: health-records-service
    spec:
      containers:
      - name: health-records-service
        image: health-recommendation-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: health-records-service
spec:
  selector:
    app: health-records-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
